
// COOKIES
	// Switch state
	var colorswitch = $.cookie('colorpickerHexagonReborn');
	
	// Set the user's selection
	function injectStyles(rule) {
  var div = $("<div />", {
    html: '&shy;<style>' + rule + '</style>'
  }).appendTo("body");    
}
	if (colorswitch == 'green') {
		
injectStyles('a:hover,a:focus,a:active{color: #00de1f;}');
injectStyles('.button:before {color: #00de1f;}');
injectStyles('ul.navlinks {border-top: 1px solid #00de1f;}');
injectStyles('.minitabs .tab > a:hover {background-color: #00de1f;}');
injectStyles('.attach-image img {border-color: #00de1f !important;}');
injectStyles('dd input, dd textarea {border: 1px solid #00de1f;}');
injectStyles('.icon, .button .icon, blockquote cite:before, .uncited:before {color: #00de1f;}');
injectStyles('.dropdown-contents a:hover {color: #00de1f;}');
injectStyles('.profile-left {border-color: #00de1f;}');
injectStyles('@media (max-width: 700px){.inputbox {border: 1px solid #00de1f;}}');
injectStyles('.smiley-box:hover {border: 1px dashed #00de1f;}');
injectStyles('@media (max-width: 700px){.smiley-box {border: 1px dashed #00de1f;}}');
injectStyles('a.responsive-tab-link.dropdown-toggle:active{border: 1px solid #00de1f;}');
injectStyles('a.responsive-tab-link.dropdown-toggle:hover{border: 1px solid #00de1f;}');
injectStyles('.header{border-bottom: 4px solid #00de1f;}');
injectStyles('.global_unread:before,.global_unread_mine:before,.announce_unread:before,.announce_unread_mine:before,.sticky_unread:before,.sticky_unread_mine:before {color: #00de1f;}');
injectStyles('.global_unread_locked:before,.global_unread_locked_mine:before,.announce_unread_locked:before,.announce_unread_locked_mine:before,.forum_unread_locked:before,.topic_unread_locked:before,.topic_unread_locked_mine:before {color: #00de1f;}');
injectStyles('.forum_link:before {color: #00de1f;}');
injectStyles('.forum_unread:before,.forum_unread_subforum:before,.topic_unread:before,.topic_unread_mine:before {color: #00de1f;}');
injectStyles('.sticky_unread_locked:before,.sticky_unread_locked_mine:before {color: #00de1f;}');
injectStyles('.topic_unread_hot:before,.topic_unread_hot_mine:before {color: #00de1f;}');
injectStyles('.pm_unread:before {color: #00de1f;}');
injectStyles('.forum_read_subforum:after{color: #00de1f;}');
injectStyles('.forum_read_locked:after,.global_read_locked:after,.global_read_locked_mine:after,.announce_read_locked:after,.announce_read_locked_mine:after,.sticky_read_locked:after,.sticky_read_locked_mine:after,.topic_read_locked:after,.topic_read_locked_mine:after{color: #00de1f;}');
injectStyles('.dropdown-contents a:hover {color: #00de1f;}');
injectStyles('h3 {border-color: #00de1f;}');
injectStyles('hr {border-color: #00de1f;}');
injectStyles('a:hover {color: #00de1f;}');
injectStyles('.forumbg .header a:hover, .forabg .header a:hover, th a:hover {color: #00de1f;}');
injectStyles('.postlink {border-bottom-color: #00de1f;color: #00de1f;}');
injectStyles('.top i {color: #00de1f;}');
injectStyles('.arrow-left:hover, .arrow-right:hover {color: #00de1f;}');
injectStyles('.wrap {border-color: #00de1f;}');
injectStyles('table.table1 tbody th {border-bottom-color: #00de1f;}');
injectStyles('dl.details dt {color: #00de1f;}');
injectStyles('.sep {color: #00de1f;}');
injectStyles('.icon.icon-red, a:hover .icon.icon-red{color: #00de1f;}');
injectStyles('.icon.icon-black, a:hover .icon.icon-black{color: #00de1f;}');
injectStyles('.jumpbox .dropdown li {border-top-color: #00de1f;}');
injectStyles('.jumpbox-cat-link:hover {background-color: #00de1f;}');
injectStyles('.jumpbox .dropdown .pointer-inner {border-color: #00de1f transparent;}');
injectStyles('.copyright {color: #00de1f;}');
injectStyles('div.rules {background-color: #00de1f;}');
injectStyles('ul.topiclist dd {border-left-color: #00de1f;}');
injectStyles('li.row strong {color: #00de1f;}');
injectStyles('.rtl li.row:hover dd {border-right-color: #00de1f;}');
injectStyles('.content h2, .panel h2 {border-bottom-color: #00de1f;}');
injectStyles('dl.faq dt {color: #00de1f;}');
injectStyles('.posthilit {background-color: #00de1f;}');
injectStyles('.signature {border-top-color: #00de1f;}');
injectStyles('.notice {border-top-color:  #00de1f;}');
injectStyles('blockquote {border-color: #00de1f;}');
injectStyles('.codebox {border-color: #00de1f;}');
injectStyles('.attachbox {border-color: #00de1f;}');
injectStyles('dl.thumbnail img {border-color: #00de1f;}');
injectStyles('dl.thumbnail dt a:hover img {border-color: #00de1f;}');
injectStyles('fieldset.polls dl {border-top-color: #00de1f;}');
injectStyles('fieldset.polls dl.voted {color: #00de1f;}');
injectStyles('.pollbar1 {background-color: #00de1f;}');
injectStyles('.postprofile {border-color: #00de1f;}');
injectStyles('.pm .postprofile {border-color: #00de1f;}');
injectStyles('.postprofile strong {color: #00de1f;}');
injectStyles('.online {border-right: 5px solid #00de1f;}');
injectStyles('.button:hover,.button:focus ,.button:active{text-shadow: 0px 0px 10px #00de1f;}');
injectStyles('.button-search:hover,.button-search-end:hover {border-color: #00de1f;}');
injectStyles('.pagination li.ellipsis span {color: #00de1f;}');
injectStyles('.panel-container h3, .panel-container hr, .cp-menu hr {border-color: #00de1f;}');
injectStyles('.cp-main .pm-message {border-color: #00de1f;}');
injectStyles('.tabs .tab > a:hover {background: #00de1f;}');
injectStyles('.tabs .activetab > a,.tabs .activetab > a:hover {background-color: #00de1f;border-color: #00de1f;}');
injectStyles('.minitabs .activetab > a,.minitabs .activetab > a:hover {background-color: #00de1f;}');
injectStyles('.responsive-tab .responsive-tab-link:before {border-color: #00de1f;}');
injectStyles('.responsive-tab .responsive-tab-link:hover:before {border-color: #00de1f;}');
injectStyles('.rtl .navigation a {background: #00de1f;}');
injectStyles('.navigation a:hover {background: #00de1f;}');
injectStyles('.navigation .active-subsection a {background: #00de1f !important;}');
injectStyles('.gallery label {border-color: #00de1f;}');
injectStyles('select {border-color: #00de1f;color: #00de1f;}');
injectStyles('fieldset dl:hover dt label {color: #00de1f;}');
injectStyles('.inputbox:hover {box-shadow: 0 0 4px #00de1f;}');
injectStyles('.inputbox:focus {box-shadow: 0 0 4px #00de1f;}');
injectStyles('a.button1, input.button1, input.button3, a.button2, input.button2 {background-color: #00de1f;}');
injectStyles('a.button1, input.button1 {border-color: #00de1f;}');
injectStyles('a.button2, input.button2, input.button3 {border-color: #00de1f;}');
injectStyles('a.button1:hover, input.button1:hover, a.button2:hover, input.button2:hover, input.button3:hover {color: #00de1f;}');
injectStyles('input.button1:focus, input.button2:focus, input.button3:focus {border-color: #00de1f;}');
injectStyles('.phpbb_alert {border-color: #00de1f;}');
injectStyles('.dropdown-extended ul li {border-top-color: #00de1f;}');
injectStyles('.dropdown-extended ul li:hover {color: #00de1f;}');
injectStyles('.dropdown-extended .header, .dropdown-extended .footer {border-color: #00de1f;}');
injectStyles('.dropdown .pointer-inner {border-color: #00de1f transparent;}');
injectStyles('.dropdown-extended .pointer-inner {border-color: #00de1f transparent;}');
injectStyles('.dropdown .dropdown-contents {border-top: 2px solid #00de1f;}');
injectStyles('.dropdown-up .dropdown-contents {border-color: #00de1f;}');
injectStyles('.dropdown li, .dropdown li li {border-color: #00de1f;}');
injectStyles('.dropdown li.separator {border-color: #00de1f;}');
injectStyles('.badge {background-color: #00de1f;}');
injectStyles('.badge:before {border-bottom: 7.22px solid #00de1f;}');
injectStyles('.badge:after {border-top: 7.22px solid #00de1f;}');
injectStyles('.pagination li.active span {color: #00de1f;}');
injectStyles('.pagination .button {background-color: #00de1f;}');
injectStyles('.pagination .button:hover, .pagination .button:focus, .pagination .button:active {background-color: #00de1f;}');
injectStyles('.pagination .button:before {border-bottom: 9.24px solid #00de1f;}');
injectStyles('.pagination .button:after {border-top: 9.24px solid #00de1f;}');
injectStyles('.row .pagination li a {background-color: #00de1f;}');
injectStyles('.row .pagination li a:before {border-bottom: 6.35px solid #00de1f;}');
injectStyles('.row .pagination li a:after {border-top: 6.35px solid #00de1f;}');
injectStyles('.custombbcode {background-color: #00de1f;}');
injectStyles('.custombbcode:hover {background-color: #00de1f; box-shadow: 0 0 4px #00de1f;}');
injectStyles('.collapse-btn:hover, .collapse-btn:focus { box-shadow: 0 0 20px 3px #00de1f;}');
injectStyles('.collapse-show {background-color: #00de1f;}');
injectStyles('.collapse-show:before {border-bottom: 5.22px solid #00de1f;}');
injectStyles('.collapse-show:after {border-top: 5.22px solid #00de1f;}');
injectStyles('.collapse-btn:hover {background-color: #00de1f;}');
injectStyles('.postlink:visited { color: #51d363; }');
injectStyles('.icon.icon-orange, a:hover .icon.icon-orange { color: #00ff24; }');
injectStyles('.jumpbox-cat-link { background-color: #00bc1a; }');
injectStyles('.pollbar2 { background-color: #06f227; }');
injectStyles('.pollbar3 { background-color: #08ef28; }');
injectStyles('.pollbar4 { background-color: #07cc23; }');
injectStyles('.pollbar5 { background-color: #08c422; }');
injectStyles('.contact-icon:before {color: #00de1f;}');
injectStyles('.site_logo { background-image: url(styles/HexagonReborn/theme/images/logogreen.png); }');
injectStyles('@media (max-width: 700px){ .logo { background-image: url(styles/HexagonReborn/theme/images/logo-green-med.png); }}');
injectStyles('.loading_indicator { background-image: url(styles/HexagonReborn/theme/images/loadinggreen.gif); }');	
    };
if (colorswitch == 'blue') {
		
injectStyles('a:hover,a:focus,a:active{color: #0092de;}');
injectStyles('.button:before {color: #0092de;}');
injectStyles('ul.navlinks {border-top: 1px solid #0092de;}');
injectStyles('.minitabs .tab > a:hover {background-color: #0092de;}');
injectStyles('.attach-image img {border-color: #0092de !important;}');
injectStyles('dd input, dd textarea {border: 1px solid #0092de;}');
injectStyles('.icon, .button .icon, blockquote cite:before, .uncited:before {color: #0092de;}');
injectStyles('.dropdown-contents a:hover {color: #0092de;}');
injectStyles('.profile-left {border-color: #0092de;}');
injectStyles('@media (max-width: 700px){.inputbox {border: 1px solid #0092de;}}');
injectStyles('.smiley-box:hover {border: 1px dashed #0092de;}');
injectStyles('@media (max-width: 700px){.smiley-box {border: 1px dashed #0092de;}}');
injectStyles('a.responsive-tab-link.dropdown-toggle:active{border: 1px solid #0092de;}');
injectStyles('a.responsive-tab-link.dropdown-toggle:hover{border: 1px solid #0092de;}');
injectStyles('.header{border-bottom: 4px solid #0092de;}');
injectStyles('.global_unread:before,.global_unread_mine:before,.announce_unread:before,.announce_unread_mine:before,.sticky_unread:before,.sticky_unread_mine:before {color: #0092de;}');
injectStyles('.global_unread_locked:before,.global_unread_locked_mine:before,.announce_unread_locked:before,.announce_unread_locked_mine:before,.forum_unread_locked:before,.topic_unread_locked:before,.topic_unread_locked_mine:before {color: #0092de;}');
injectStyles('.forum_link:before {color: #0092de;}');
injectStyles('.forum_unread:before,.forum_unread_subforum:before,.topic_unread:before,.topic_unread_mine:before {color: #0092de;}');
injectStyles('.sticky_unread_locked:before,.sticky_unread_locked_mine:before {color: #0092de;}');
injectStyles('.topic_unread_hot:before,.topic_unread_hot_mine:before {color: #0092de;}');
injectStyles('.pm_unread:before {color: #0092de;}');
injectStyles('.forum_read_subforum:after{color: #0092de;}');
injectStyles('.forum_read_locked:after,.global_read_locked:after,.global_read_locked_mine:after,.announce_read_locked:after,.announce_read_locked_mine:after,.sticky_read_locked:after,.sticky_read_locked_mine:after,.topic_read_locked:after,.topic_read_locked_mine:after{color: #0092de;}');
injectStyles('.dropdown-contents a:hover {color: #0092de;}');
injectStyles('h3 {border-color: #0092de;}');
injectStyles('hr {border-color: #0092de;}');
injectStyles('a:hover {color: #0092de;}');
injectStyles('.forumbg .header a:hover, .forabg .header a:hover, th a:hover {color: #0092de;}');
injectStyles('.postlink {border-bottom-color: #0092de;color: #0092de;}');
injectStyles('.top i {color: #0092de;}');
injectStyles('.arrow-left:hover, .arrow-right:hover {color: #0092de;}');
injectStyles('.wrap {border-color: #0092de;}');
injectStyles('table.table1 tbody th {border-bottom-color: #0092de;}');
injectStyles('dl.details dt {color: #0092de;}');
injectStyles('.sep {color: #0092de;}');
injectStyles('.icon.icon-red, a:hover .icon.icon-red{color: #0092de;}');
injectStyles('.icon.icon-black, a:hover .icon.icon-black{color: #0092de;}');
injectStyles('.jumpbox .dropdown li {border-top-color: #0092de;}');
injectStyles('.jumpbox-cat-link:hover {background-color: #0092de;}');
injectStyles('.jumpbox .dropdown .pointer-inner {border-color: #0092de transparent;}');
injectStyles('.copyright {color: #0092de;}');
injectStyles('div.rules {background-color: #0092de;}');
injectStyles('ul.topiclist dd {border-left-color: #0092de;}');
injectStyles('li.row strong {color: #0092de;}');
injectStyles('.rtl li.row:hover dd {border-right-color: #0092de;}');
injectStyles('.content h2, .panel h2 {border-bottom-color: #0092de;}');
injectStyles('dl.faq dt {color: #0092de;}');
injectStyles('.posthilit {background-color: #0092de;}');
injectStyles('.signature {border-top-color: #0092de;}');
injectStyles('.notice {border-top-color:  #0092de;}');
injectStyles('blockquote {border-color: #0092de;}');
injectStyles('.codebox {border-color: #0092de;}');
injectStyles('.attachbox {border-color: #0092de;}');
injectStyles('dl.thumbnail img {border-color: #0092de;}');
injectStyles('dl.thumbnail dt a:hover img {border-color: #0092de;}');
injectStyles('fieldset.polls dl {border-top-color: #0092de;}');
injectStyles('fieldset.polls dl.voted {color: #0092de;}');
injectStyles('.pollbar1 {background-color: #0092de;}');
injectStyles('.postprofile {border-color: #0092de;}');
injectStyles('.pm .postprofile {border-color: #0092de;}');
injectStyles('.postprofile strong {color: #0092de;}');
injectStyles('.online {border-right: 5px solid #0092de;}');
injectStyles('.button:hover,.button:focus ,.button:active{text-shadow: 0px 0px 10px #0092de;}');
injectStyles('.button-search:hover,.button-search-end:hover {border-color: #0092de;}');
injectStyles('.pagination li.ellipsis span {color: #0092de;}');
injectStyles('.panel-container h3, .panel-container hr, .cp-menu hr {border-color: #0092de;}');
injectStyles('.cp-main .pm-message {border-color: #0092de;}');
injectStyles('.tabs .tab > a:hover {background: #0092de;}');
injectStyles('.tabs .activetab > a,.tabs .activetab > a:hover {background-color: #0092de;border-color: #0092de;}');
injectStyles('.minitabs .activetab > a,.minitabs .activetab > a:hover {background-color: #0092de;}');
injectStyles('.responsive-tab .responsive-tab-link:before {border-color: #0092de;}');
injectStyles('.responsive-tab .responsive-tab-link:hover:before {border-color: #0092de;}');
injectStyles('.rtl .navigation a {background: #0092de;}');
injectStyles('.navigation a:hover {background: #0092de;}');
injectStyles('.navigation .active-subsection a {background: #0092de !important;}');
injectStyles('.gallery label {border-color: #0092de;}');
injectStyles('select {border-color: #0092de;color: #0092de;}');
injectStyles('fieldset dl:hover dt label {color: #0092de;}');
injectStyles('.inputbox:hover {box-shadow: 0 0 4px #0092de;}');
injectStyles('.inputbox:focus {box-shadow: 0 0 4px #0092de;}');
injectStyles('a.button1, input.button1, input.button3, a.button2, input.button2 {background-color: #0092de;}');
injectStyles('a.button1, input.button1 {border-color: #0092de;}');
injectStyles('a.button2, input.button2, input.button3 {border-color: #0092de;}');
injectStyles('a.button1:hover, input.button1:hover, a.button2:hover, input.button2:hover, input.button3:hover {color: #0092de;}');
injectStyles('input.button1:focus, input.button2:focus, input.button3:focus {border-color: #0092de;}');
injectStyles('.phpbb_alert {border-color: #0092de;}');
injectStyles('.dropdown-extended ul li {border-top-color: #0092de;}');
injectStyles('.dropdown-extended ul li:hover {color: #0092de;}');
injectStyles('.dropdown-extended .header, .dropdown-extended .footer {border-color: #0092de;}');
injectStyles('.dropdown .pointer-inner {border-color: #0092de transparent;}');
injectStyles('.dropdown-extended .pointer-inner {border-color: #0092de transparent;}');
injectStyles('.dropdown .dropdown-contents {border-top: 2px solid #0092de;}');
injectStyles('.dropdown-up .dropdown-contents {border-color: #0092de;}');
injectStyles('.dropdown li, .dropdown li li {border-color: #0092de;}');
injectStyles('.dropdown li.separator {border-color: #0092de;}');
injectStyles('.badge {background-color: #0092de;}');
injectStyles('.badge:before {border-bottom: 7.22px solid #0092de;}');
injectStyles('.badge:after {border-top: 7.22px solid #0092de;}');
injectStyles('.pagination li.active span {color: #0092de;}');
injectStyles('.pagination .button {background-color: #0092de;}');
injectStyles('.pagination .button:hover, .pagination .button:focus, .pagination .button:active {background-color: #0092de;}');
injectStyles('.pagination .button:before {border-bottom: 9.24px solid #0092de;}');
injectStyles('.pagination .button:after {border-top: 9.24px solid #0092de;}');
injectStyles('.row .pagination li a {background-color: #0092de;}');
injectStyles('.row .pagination li a:before {border-bottom: 6.35px solid #0092de;}');
injectStyles('.row .pagination li a:after {border-top: 6.35px solid #0092de;}');
injectStyles('.custombbcode {background-color: #0092de;}');
injectStyles('.custombbcode:hover {background-color: #0092de; box-shadow: 0 0 4px #0092de;}');
injectStyles('.collapse-btn:hover, .collapse-btn:focus { box-shadow: 0 0 20px 3px #0092de;}');
injectStyles('.collapse-show {background-color: #0092de;}');
injectStyles('.collapse-show:before {border-bottom: 5.22px solid #0092de;}');
injectStyles('.collapse-show:after {border-top: 5.22px solid #0092de;}');
injectStyles('.collapse-btn:hover {background-color: #0092de;}');
injectStyles('.postlink:visited { color: #51a7d3; }');
injectStyles('.icon.icon-orange, a:hover .icon.icon-orange { color: #00a7fe; }');
injectStyles('.jumpbox-cat-link { background-color: #00a4bd; }');
injectStyles('.pollbar2 { background-color: #06a2f3; }');
injectStyles('.pollbar3 { background-color: #079fee; }');
injectStyles('.pollbar4 { background-color: #0789cd; }');
injectStyles('.pollbar5 { background-color: #0884c5; }');
injectStyles('.contact-icon:before {color: #0092de;}');
injectStyles('.site_logo { background-image: url(styles/HexagonReborn/theme/images/logoblue.png); }');
injectStyles('@media (max-width: 700px){ .logo { background-image: url(styles/HexagonReborn/theme/images/logo-blue-med.png); }}');
injectStyles('.loading_indicator { background-image: url(styles/HexagonReborn/theme/images/loadingblue.gif); }');		
    };	
if (colorswitch == 'cyan') {
		
injectStyles('a:hover,a:focus,a:active{color: #00c1de;}');
injectStyles('.button:before {color: #00c1de;}');
injectStyles('ul.navlinks {border-top: 1px solid #00c1de;}');
injectStyles('.minitabs .tab > a:hover {background-color: #00c1de;}');
injectStyles('.attach-image img {border-color: #00c1de !important;}');
injectStyles('dd input, dd textarea {border: 1px solid #00c1de;}');
injectStyles('.icon, .button .icon, blockquote cite:before, .uncited:before {color: #00c1de;}');
injectStyles('.dropdown-contents a:hover {color: #00c1de;}');
injectStyles('.profile-left {border-color: #00c1de;}');
injectStyles('@media (max-width: 700px){.inputbox {border: 1px solid #00c1de;}}');
injectStyles('.smiley-box:hover {border: 1px dashed #00c1de;}');
injectStyles('@media (max-width: 700px){.smiley-box {border: 1px dashed #00c1de;}}');
injectStyles('a.responsive-tab-link.dropdown-toggle:active{border: 1px solid #00c1de;}');
injectStyles('a.responsive-tab-link.dropdown-toggle:hover{border: 1px solid #00c1de;}');
injectStyles('.header{border-bottom: 4px solid #00c1de;}');
injectStyles('.global_unread:before,.global_unread_mine:before,.announce_unread:before,.announce_unread_mine:before,.sticky_unread:before,.sticky_unread_mine:before {color: #00c1de;}');
injectStyles('.global_unread_locked:before,.global_unread_locked_mine:before,.announce_unread_locked:before,.announce_unread_locked_mine:before,.forum_unread_locked:before,.topic_unread_locked:before,.topic_unread_locked_mine:before {color: #00c1de;}');
injectStyles('.forum_link:before {color: #00c1de;}');
injectStyles('.forum_unread:before,.forum_unread_subforum:before,.topic_unread:before,.topic_unread_mine:before {color: #00c1de;}');
injectStyles('.sticky_unread_locked:before,.sticky_unread_locked_mine:before {color: #00c1de;}');
injectStyles('.topic_unread_hot:before,.topic_unread_hot_mine:before {color: #00c1de;}');
injectStyles('.pm_unread:before {color: #00c1de;}');
injectStyles('.forum_read_subforum:after{color: #00c1de;}');
injectStyles('.forum_read_locked:after,.global_read_locked:after,.global_read_locked_mine:after,.announce_read_locked:after,.announce_read_locked_mine:after,.sticky_read_locked:after,.sticky_read_locked_mine:after,.topic_read_locked:after,.topic_read_locked_mine:after{color: #00c1de;}');
injectStyles('.dropdown-contents a:hover {color: #00c1de;}');
injectStyles('h3 {border-color: #00c1de;}');
injectStyles('hr {border-color: #00c1de;}');
injectStyles('a:hover {color: #00c1de;}');
injectStyles('.forumbg .header a:hover, .forabg .header a:hover, th a:hover {color: #00c1de;}');
injectStyles('.postlink {border-bottom-color: #00c1de;color: #00c1de;}');
injectStyles('.top i {color: #00c1de;}');
injectStyles('.arrow-left:hover, .arrow-right:hover {color: #00c1de;}');
injectStyles('.wrap {border-color: #00c1de;}');
injectStyles('table.table1 tbody th {border-bottom-color: #00c1de;}');
injectStyles('dl.details dt {color: #00c1de;}');
injectStyles('.sep {color: #00c1de;}');
injectStyles('.icon.icon-red, a:hover .icon.icon-red{color: #00c1de;}');
injectStyles('.icon.icon-black, a:hover .icon.icon-black{color: #00c1de;}');
injectStyles('.jumpbox .dropdown li {border-top-color: #00c1de;}');
injectStyles('.jumpbox-cat-link:hover {background-color: #00c1de;}');
injectStyles('.jumpbox .dropdown .pointer-inner {border-color: #00c1de transparent;}');
injectStyles('.copyright {color: #00c1de;}');
injectStyles('div.rules {background-color: #00c1de;}');
injectStyles('ul.topiclist dd {border-left-color: #00c1de;}');
injectStyles('li.row strong {color: #00c1de;}');
injectStyles('.rtl li.row:hover dd {border-right-color: #00c1de;}');
injectStyles('.content h2, .panel h2 {border-bottom-color: #00c1de;}');
injectStyles('dl.faq dt {color: #00c1de;}');
injectStyles('.posthilit {background-color: #00c1de;}');
injectStyles('.signature {border-top-color: #00c1de;}');
injectStyles('.notice {border-top-color:  #00c1de;}');
injectStyles('blockquote {border-color: #00c1de;}');
injectStyles('.codebox {border-color: #00c1de;}');
injectStyles('.attachbox {border-color: #00c1de;}');
injectStyles('dl.thumbnail img {border-color: #00c1de;}');
injectStyles('dl.thumbnail dt a:hover img {border-color: #00c1de;}');
injectStyles('fieldset.polls dl {border-top-color: #00c1de;}');
injectStyles('fieldset.polls dl.voted {color: #00c1de;}');
injectStyles('.pollbar1 {background-color: #00c1de;}');
injectStyles('.postprofile {border-color: #00c1de;}');
injectStyles('.pm .postprofile {border-color: #00c1de;}');
injectStyles('.postprofile strong {color: #00c1de;}');
injectStyles('.online {border-right: 5px solid #00c1de;}');
injectStyles('.button:hover,.button:focus ,.button:active{text-shadow: 0px 0px 10px #00c1de;}');
injectStyles('.button-search:hover,.button-search-end:hover {border-color: #00c1de;}');
injectStyles('.pagination li.ellipsis span {color: #00c1de;}');
injectStyles('.panel-container h3, .panel-container hr, .cp-menu hr {border-color: #00c1de;}');
injectStyles('.cp-main .pm-message {border-color: #00c1de;}');
injectStyles('.tabs .tab > a:hover {background: #00c1de;}');
injectStyles('.tabs .activetab > a,.tabs .activetab > a:hover {background-color: #00c1de;border-color: #00c1de;}');
injectStyles('.minitabs .activetab > a,.minitabs .activetab > a:hover {background-color: #00c1de;}');
injectStyles('.responsive-tab .responsive-tab-link:before {border-color: #00c1de;}');
injectStyles('.responsive-tab .responsive-tab-link:hover:before {border-color: #00c1de;}');
injectStyles('.rtl .navigation a {background: #00c1de;}');
injectStyles('.navigation a:hover {background: #00c1de;}');
injectStyles('.navigation .active-subsection a {background: #00c1de !important;}');
injectStyles('.gallery label {border-color: #00c1de;}');
injectStyles('select {border-color: #00c1de;color: #00c1de;}');
injectStyles('fieldset dl:hover dt label {color: #00c1de;}');
injectStyles('.inputbox:hover {box-shadow: 0 0 4px #00c1de;}');
injectStyles('.inputbox:focus {box-shadow: 0 0 4px #00c1de;}');
injectStyles('a.button1, input.button1, input.button3, a.button2, input.button2 {background-color: #00c1de;}');
injectStyles('a.button1, input.button1 {border-color: #00c1de;}');
injectStyles('a.button2, input.button2, input.button3 {border-color: #00c1de;}');
injectStyles('a.button1:hover, input.button1:hover, a.button2:hover, input.button2:hover, input.button3:hover {color: #00c1de;}');
injectStyles('input.button1:focus, input.button2:focus, input.button3:focus {border-color: #00c1de;}');
injectStyles('.phpbb_alert {border-color: #00c1de;}');
injectStyles('.dropdown-extended ul li {border-top-color: #00c1de;}');
injectStyles('.dropdown-extended ul li:hover {color: #00c1de;}');
injectStyles('.dropdown-extended .header, .dropdown-extended .footer {border-color: #00c1de;}');
injectStyles('.dropdown .pointer-inner {border-color: #00c1de transparent;}');
injectStyles('.dropdown-extended .pointer-inner {border-color: #00c1de transparent;}');
injectStyles('.dropdown .dropdown-contents {border-top: 2px solid #00c1de;}');
injectStyles('.dropdown-up .dropdown-contents {border-color: #00c1de;}');
injectStyles('.dropdown li, .dropdown li li {border-color: #00c1de;}');
injectStyles('.dropdown li.separator {border-color: #00c1de;}');
injectStyles('.badge {background-color: #00c1de;}');
injectStyles('.badge:before {border-bottom: 7.22px solid #00c1de;}');
injectStyles('.badge:after {border-top: 7.22px solid #00c1de;}');
injectStyles('.pagination li.active span {color: #00c1de;}');
injectStyles('.pagination .button {background-color: #00c1de;}');
injectStyles('.pagination .button:hover, .pagination .button:focus, .pagination .button:active {background-color: #00c1de;}');
injectStyles('.pagination .button:before {border-bottom: 9.24px solid #00c1de;}');
injectStyles('.pagination .button:after {border-top: 9.24px solid #00c1de;}');
injectStyles('.row .pagination li a {background-color: #00c1de;}');
injectStyles('.row .pagination li a:before {border-bottom: 6.35px solid #00c1de;}');
injectStyles('.row .pagination li a:after {border-top: 6.35px solid #00c1de;}');
injectStyles('.custombbcode {background-color: #00c1de;}');
injectStyles('.custombbcode:hover {background-color: #00c1de; box-shadow: 0 0 4px #00c1de;}');
injectStyles('.collapse-btn:hover, .collapse-btn:focus { box-shadow: 0 0 20px 3px #00c1de;}');
injectStyles('.collapse-show {background-color: #00c1de;}');
injectStyles('.collapse-show:before {border-bottom: 5.22px solid #00c1de;}');
injectStyles('.collapse-show:after {border-top: 5.22px solid #00c1de;}');
injectStyles('.collapse-btn:hover {background-color: #00c1de;}');
injectStyles('.postlink:visited { color: #51c1d2; }');
injectStyles('.icon.icon-orange, a:hover .icon.icon-orange { color: #01deff; }');
injectStyles('.jumpbox-cat-link { background-color: #00a4bd; }');
injectStyles('.pollbar2 { background-color: #06d4f3; }');
injectStyles('.pollbar3 { background-color: #07d0ee; }');
injectStyles('.pollbar4 { background-color: #07b2cc; }');
injectStyles('.pollbar5 { background-color: #08acc5; }');
injectStyles('.contact-icon:before {color: #00c1de;}');
injectStyles('@media (max-width: 700px){ .inputbox { border: 1px solid #00c1de; }}');
injectStyles('@media (max-width: 700px){ .smiley-box { border: 1px dashed #00c1de; }}');	
injectStyles('.site_logo { background-image: url(styles/HexagonReborn/theme/images/logocyan.png); }');
injectStyles('@media (max-width: 700px){ .logo { background-image: url(styles/HexagonReborn/theme/images/logo-cyan-med.png); }}');
injectStyles('.loading_indicator { background-image: url(styles/HexagonReborn/theme/images/loadingcyan.gif); }');	
    };	
if (colorswitch == 'violet') {
		
injectStyles('a:hover,a:focus,a:active{color: #7d00de;}');
injectStyles('.button:before {color: #7d00de;}');
injectStyles('ul.navlinks {border-top: 1px solid #7d00de;}');
injectStyles('.minitabs .tab > a:hover {background-color: #7d00de;}');
injectStyles('.attach-image img {border-color: #7d00de !important;}');
injectStyles('dd input, dd textarea {border: 1px solid #7d00de;}');
injectStyles('.icon, .button .icon, blockquote cite:before, .uncited:before {color: #7d00de;}');
injectStyles('.dropdown-contents a:hover {color: #7d00de;}');
injectStyles('.profile-left {border-color: #7d00de;}');
injectStyles('@media (max-width: 700px){.inputbox {border: 1px solid #7d00de;}}');
injectStyles('.smiley-box:hover {border: 1px dashed #7d00de;}');
injectStyles('@media (max-width: 700px){.smiley-box {border: 1px dashed #7d00de;}}');
injectStyles('a.responsive-tab-link.dropdown-toggle:active{border: 1px solid #7d00de;}');
injectStyles('a.responsive-tab-link.dropdown-toggle:hover{border: 1px solid #7d00de;}');
injectStyles('.header{border-bottom: 4px solid #7d00de;}');
injectStyles('.global_unread:before,.global_unread_mine:before,.announce_unread:before,.announce_unread_mine:before,.sticky_unread:before,.sticky_unread_mine:before {color: #7d00de;}');
injectStyles('.global_unread_locked:before,.global_unread_locked_mine:before,.announce_unread_locked:before,.announce_unread_locked_mine:before,.forum_unread_locked:before,.topic_unread_locked:before,.topic_unread_locked_mine:before {color: #7d00de;}');
injectStyles('.forum_link:before {color: #7d00de;}');
injectStyles('.forum_unread:before,.forum_unread_subforum:before,.topic_unread:before,.topic_unread_mine:before {color: #7d00de;}');
injectStyles('.sticky_unread_locked:before,.sticky_unread_locked_mine:before {color: #7d00de;}');
injectStyles('.topic_unread_hot:before,.topic_unread_hot_mine:before {color: #7d00de;}');
injectStyles('.pm_unread:before {color: #7d00de;}');
injectStyles('.forum_read_subforum:after{color: #7d00de;}');
injectStyles('.forum_read_locked:after,.global_read_locked:after,.global_read_locked_mine:after,.announce_read_locked:after,.announce_read_locked_mine:after,.sticky_read_locked:after,.sticky_read_locked_mine:after,.topic_read_locked:after,.topic_read_locked_mine:after{color: #7d00de;}');
injectStyles('.dropdown-contents a:hover {color: #7d00de;}');
injectStyles('h3 {border-color: #7d00de;}');
injectStyles('hr {border-color: #7d00de;}');
injectStyles('a:hover {color: #7d00de;}');
injectStyles('.forumbg .header a:hover, .forabg .header a:hover, th a:hover {color: #7d00de;}');
injectStyles('.postlink {border-bottom-color: #7d00de;color: #7d00de;}');
injectStyles('.top i {color: #7d00de;}');
injectStyles('.arrow-left:hover, .arrow-right:hover {color: #7d00de;}');
injectStyles('.wrap {border-color: #7d00de;}');
injectStyles('table.table1 tbody th {border-bottom-color: #7d00de;}');
injectStyles('dl.details dt {color: #7d00de;}');
injectStyles('.sep {color: #7d00de;}');
injectStyles('.icon.icon-red, a:hover .icon.icon-red{color: #7d00de;}');
injectStyles('.icon.icon-black, a:hover .icon.icon-black{color: #7d00de;}');
injectStyles('.jumpbox .dropdown li {border-top-color: #7d00de;}');
injectStyles('.jumpbox-cat-link:hover {background-color: #7d00de;}');
injectStyles('.jumpbox .dropdown .pointer-inner {border-color: #7d00de transparent;}');
injectStyles('.copyright {color: #7d00de;}');
injectStyles('div.rules {background-color: #7d00de;}');
injectStyles('ul.topiclist dd {border-left-color: #7d00de;}');
injectStyles('li.row strong {color: #7d00de;}');
injectStyles('.rtl li.row:hover dd {border-right-color: #7d00de;}');
injectStyles('.content h2, .panel h2 {border-bottom-color: #7d00de;}');
injectStyles('dl.faq dt {color: #7d00de;}');
injectStyles('.posthilit {background-color: #7d00de;}');
injectStyles('.signature {border-top-color: #7d00de;}');
injectStyles('.notice {border-top-color:  #7d00de;}');
injectStyles('blockquote {border-color: #7d00de;}');
injectStyles('.codebox {border-color: #7d00de;}');
injectStyles('.attachbox {border-color: #7d00de;}');
injectStyles('dl.thumbnail img {border-color: #7d00de;}');
injectStyles('dl.thumbnail dt a:hover img {border-color: #7d00de;}');
injectStyles('fieldset.polls dl {border-top-color: #7d00de;}');
injectStyles('fieldset.polls dl.voted {color: #7d00de;}');
injectStyles('.pollbar1 {background-color: #7d00de;}');
injectStyles('.postprofile {border-color: #7d00de;}');
injectStyles('.pm .postprofile {border-color: #7d00de;}');
injectStyles('.postprofile strong {color: #7d00de;}');
injectStyles('.online {border-right: 5px solid #7d00de;}');
injectStyles('.button:hover,.button:focus ,.button:active{text-shadow: 0px 0px 10px #7d00de;}');
injectStyles('.button-search:hover,.button-search-end:hover {border-color: #7d00de;}');
injectStyles('.pagination li.ellipsis span {color: #7d00de;}');
injectStyles('.panel-container h3, .panel-container hr, .cp-menu hr {border-color: #7d00de;}');
injectStyles('.cp-main .pm-message {border-color: #7d00de;}');
injectStyles('.tabs .tab > a:hover {background: #7d00de;}');
injectStyles('.tabs .activetab > a,.tabs .activetab > a:hover {background-color: #7d00de;border-color: #7d00de;}');
injectStyles('.minitabs .activetab > a,.minitabs .activetab > a:hover {background-color: #7d00de;}');
injectStyles('.responsive-tab .responsive-tab-link:before {border-color: #7d00de;}');
injectStyles('.responsive-tab .responsive-tab-link:hover:before {border-color: #7d00de;}');
injectStyles('.rtl .navigation a {background: #7d00de;}');
injectStyles('.navigation a:hover {background: #7d00de;}');
injectStyles('.navigation .active-subsection a {background: #7d00de !important;}');
injectStyles('.gallery label {border-color: #7d00de;}');
injectStyles('select {border-color: #7d00de;color: #7d00de;}');
injectStyles('fieldset dl:hover dt label {color: #7d00de;}');
injectStyles('.inputbox:hover {box-shadow: 0 0 4px #7d00de;}');
injectStyles('.inputbox:focus {box-shadow: 0 0 4px #7d00de;}');
injectStyles('a.button1, input.button1, input.button3, a.button2, input.button2 {background-color: #7d00de;}');
injectStyles('a.button1, input.button1 {border-color: #7d00de;}');
injectStyles('a.button2, input.button2, input.button3 {border-color: #7d00de;}');
injectStyles('a.button1:hover, input.button1:hover, a.button2:hover, input.button2:hover, input.button3:hover {color: #7d00de;}');
injectStyles('input.button1:focus, input.button2:focus, input.button3:focus {border-color: #7d00de;}');
injectStyles('.phpbb_alert {border-color: #7d00de;}');
injectStyles('.dropdown-extended ul li {border-top-color: #7d00de;}');
injectStyles('.dropdown-extended ul li:hover {color: #7d00de;}');
injectStyles('.dropdown-extended .header, .dropdown-extended .footer {border-color: #7d00de;}');
injectStyles('.dropdown .pointer-inner {border-color: #7d00de transparent;}');
injectStyles('.dropdown-extended .pointer-inner {border-color: #7d00de transparent;}');
injectStyles('.dropdown .dropdown-contents {border-top: 2px solid #7d00de;}');
injectStyles('.dropdown-up .dropdown-contents {border-color: #7d00de;}');
injectStyles('.dropdown li, .dropdown li li {border-color: #7d00de;}');
injectStyles('.dropdown li.separator {border-color: #7d00de;}');
injectStyles('.badge {background-color: #7d00de;}');
injectStyles('.badge:before {border-bottom: 7.22px solid #7d00de;}');
injectStyles('.badge:after {border-top: 7.22px solid #7d00de;}');
injectStyles('.pagination li.active span {color: #7d00de;}');
injectStyles('.pagination .button {background-color: #7d00de;}');
injectStyles('.pagination .button:hover, .pagination .button:focus, .pagination .button:active {background-color: #7d00de;}');
injectStyles('.pagination .button:before {border-bottom: 9.24px solid #7d00de;}');
injectStyles('.pagination .button:after {border-top: 9.24px solid #7d00de;}');
injectStyles('.row .pagination li a {background-color: #7d00de;}');
injectStyles('.row .pagination li a:before {border-bottom: 6.35px solid #7d00de;}');
injectStyles('.row .pagination li a:after {border-top: 6.35px solid #7d00de;}');
injectStyles('.custombbcode {background-color: #7d00de;}');
injectStyles('.custombbcode:hover {background-color: #7d00de; box-shadow: 0 0 4px #7d00de;}');
injectStyles('.collapse-btn:hover, .collapse-btn:focus { box-shadow: 0 0 20px 3px #7d00de;}');
injectStyles('.collapse-show {background-color: #7d00de;}');
injectStyles('.collapse-show:before {border-bottom: 5.22px solid #7d00de;}');
injectStyles('.collapse-show:after {border-top: 5.22px solid #7d00de;}');
injectStyles('.collapse-btn:hover {background-color: #7d00de;}');
injectStyles('.postlink:visited { color: #9b52d3; }');
injectStyles('.icon.icon-orange, a:hover .icon.icon-orange { color: #9001ff; }');
injectStyles('.jumpbox-cat-link { background-color: #6a00bd; }');
injectStyles('.pollbar2 { background-color: #8b06f3; }');
injectStyles('.pollbar3 { background-color: #8a08ef; }');
injectStyles('.pollbar4 { background-color: #7606cd; }');
injectStyles('.pollbar5 { background-color: #7207c5; }');
injectStyles('.contact-icon:before {color: #7d00de;}');
injectStyles('.site_logo { background-image: url(styles/HexagonReborn/theme/images/logoviolet.png); }');
injectStyles('@media (max-width: 700px){ .logo { background-image: url(styles/HexagonReborn/theme/images/logo-violet-med.png); }}');
injectStyles('.loading_indicator { background-image: url(styles/HexagonReborn/theme/images/loadingviolet.gif); }');		
    };

$(document).ready(function() {
// COLORSWITCH:

	// When orange is clicked:
    $('.colororange').click(function() {
		
injectStyles('a:hover,a:focus,a:active{color: #DE7300;}');
injectStyles('.button:before {color: #de7300;}');
injectStyles('ul.navlinks {border-top: 1px solid #de7300;}');
injectStyles('.minitabs .tab > a:hover {background-color: #de7300;}');
injectStyles('.attach-image img {border-color: #de7300 !important;}');
injectStyles('dd input, dd textarea {border: 1px solid #de7300;}');
injectStyles('.icon, .button .icon, blockquote cite:before, .uncited:before {color: #de7300;}');
injectStyles('.dropdown-contents a:hover {color: #de7300;}');
injectStyles('.profile-left {border-color: #de7300;}');
injectStyles('@media (max-width: 700px){.inputbox {border: 1px solid #de7300;}}');
injectStyles('.smiley-box:hover {border: 1px dashed #de7300;}');
injectStyles('@media (max-width: 700px){.smiley-box {border: 1px dashed #de7300;}}');
injectStyles('a.responsive-tab-link.dropdown-toggle:active{border: 1px solid #de7300;}');
injectStyles('a.responsive-tab-link.dropdown-toggle:hover{border: 1px solid #de7300;}');
injectStyles('.header{border-bottom: 4px solid #de7300;}');
injectStyles('.global_unread:before,.global_unread_mine:before,.announce_unread:before,.announce_unread_mine:before,.sticky_unread:before,.sticky_unread_mine:before {color: #de7300;}');
injectStyles('.global_unread_locked:before,.global_unread_locked_mine:before,.announce_unread_locked:before,.announce_unread_locked_mine:before,.forum_unread_locked:before,.topic_unread_locked:before,.topic_unread_locked_mine:before {color: #de7300;}');
injectStyles('.forum_link:before {color: #de7300;}');
injectStyles('.forum_unread:before,.forum_unread_subforum:before,.topic_unread:before,.topic_unread_mine:before {color: #de7300;}');
injectStyles('.sticky_unread_locked:before,.sticky_unread_locked_mine:before {color: #de7300;}');
injectStyles('.topic_unread_hot:before,.topic_unread_hot_mine:before {color: #de7300;}');
injectStyles('.pm_unread:before {color: #de7300;}');
injectStyles('.forum_read_subforum:after{color: #de7300;}');
injectStyles('.forum_read_locked:after,.global_read_locked:after,.global_read_locked_mine:after,.announce_read_locked:after,.announce_read_locked_mine:after,.sticky_read_locked:after,.sticky_read_locked_mine:after,.topic_read_locked:after,.topic_read_locked_mine:after{color: #de7300;}');
injectStyles('.dropdown-contents a:hover {color: #de7300;}');
injectStyles('h3 {border-color: #de7300;}');
injectStyles('hr {border-color: #de7300;}');
injectStyles('a:hover {color: #DE7300;}');
injectStyles('.forumbg .header a:hover, .forabg .header a:hover, th a:hover {color: #de7300;}');
injectStyles('.postlink {border-bottom-color: #de7300;color: #de7300;}');
injectStyles('.top i {color: #de7300;}');
injectStyles('.arrow-left:hover, .arrow-right:hover {color: #DE7300;}');
injectStyles('.wrap {border-color: #de7300;}');
injectStyles('table.table1 tbody th {border-bottom-color: #de7300;}');
injectStyles('dl.details dt {color: #de7300;}');
injectStyles('.sep {color: #de7300;}');
injectStyles('.icon.icon-red, a:hover .icon.icon-red{color: #de7300;}');
injectStyles('.icon.icon-black, a:hover .icon.icon-black{color: #de7300;}');
injectStyles('.jumpbox .dropdown li {border-top-color: #de7300;}');
injectStyles('.jumpbox-cat-link:hover {background-color: #de7300;}');
injectStyles('.jumpbox .dropdown .pointer-inner {border-color: #de7300 transparent;}');
injectStyles('.copyright {color: #DE7300;}');
injectStyles('div.rules {background-color: #de7300;}');
injectStyles('ul.topiclist dd {border-left-color: #de7300;}');
injectStyles('li.row strong {color: #de7300;}');
injectStyles('.rtl li.row:hover dd {border-right-color: #de7300;}');
injectStyles('.content h2, .panel h2 {border-bottom-color: #de7300;}');
injectStyles('dl.faq dt {color: #de7300;}');
injectStyles('.posthilit {background-color: #de7300;}');
injectStyles('.signature {border-top-color: #de7300;}');
injectStyles('.notice {border-top-color:  #de7300;}');
injectStyles('blockquote {border-color: #de7300;}');
injectStyles('.codebox {border-color: #de7300;}');
injectStyles('.attachbox {border-color: #de7300;}');
injectStyles('dl.thumbnail img {border-color: #de7300;}');
injectStyles('dl.thumbnail dt a:hover img {border-color: #de7300;}');
injectStyles('fieldset.polls dl {border-top-color: #de7300;}');
injectStyles('fieldset.polls dl.voted {color: #de7300;}');
injectStyles('.pollbar1 {background-color: #de7300;}');
injectStyles('.postprofile {border-color: #de7300;}');
injectStyles('.pm .postprofile {border-color: #de7300;}');
injectStyles('.postprofile strong {color: #de7300;}');
injectStyles('.online {border-right: 5px solid #de7300;}');
injectStyles('.button:hover,.button:focus ,.button:active{text-shadow: 0px 0px 10px #de7300;}');
injectStyles('.button-search:hover,.button-search-end:hover {border-color: #de7300;}');
injectStyles('.pagination li.ellipsis span {color: #de7300;}');
injectStyles('.panel-container h3, .panel-container hr, .cp-menu hr {border-color: #de7300;}');
injectStyles('.cp-main .pm-message {border-color: #de7300;}');
injectStyles('.tabs .tab > a:hover {background: #de7300;}');
injectStyles('.tabs .activetab > a,.tabs .activetab > a:hover {background-color: #de7300;border-color: #de7300;}');
injectStyles('.minitabs .activetab > a,.minitabs .activetab > a:hover {background-color: #de7300;}');
injectStyles('.responsive-tab .responsive-tab-link:before {border-color: #de7300;}');
injectStyles('.responsive-tab .responsive-tab-link:hover:before {border-color: #de7300;}');
injectStyles('.rtl .navigation a {background: #de7300;}');
injectStyles('.navigation a:hover {background: #de7300;}');
injectStyles('.navigation .active-subsection a {background: #de7300 !important;}');
injectStyles('.gallery label {border-color: #de7300;}');
injectStyles('select {border-color: #de7300;color: #de7300;}');
injectStyles('fieldset dl:hover dt label {color: #de7300;}');
injectStyles('.inputbox:hover {box-shadow: 0 0 4px #de7300;}');
injectStyles('.inputbox:focus {box-shadow: 0 0 4px #de7300;}');
injectStyles('a.button1, input.button1, input.button3, a.button2, input.button2 {background-color: #de7300;}');
injectStyles('a.button1, input.button1 {border-color: #de7300;}');
injectStyles('a.button2, input.button2, input.button3 {border-color: #de7300;}');
injectStyles('a.button1:hover, input.button1:hover, a.button2:hover, input.button2:hover, input.button3:hover {color: #de7300;}');
injectStyles('input.button1:focus, input.button2:focus, input.button3:focus {border-color: #de7300;}');
injectStyles('.phpbb_alert {border-color: #de7300;}');
injectStyles('.dropdown-extended ul li {border-top-color: #de7300;}');
injectStyles('.dropdown-extended ul li:hover {color: #de7300;}');
injectStyles('.dropdown-extended .header, .dropdown-extended .footer {border-color: #de7300;}');
injectStyles('.dropdown .pointer-inner {border-color: #de7300 transparent;}');
injectStyles('.dropdown-extended .pointer-inner {border-color: #de7300 transparent;}');
injectStyles('.dropdown .dropdown-contents {border-top: 2px solid #de7300;}');
injectStyles('.dropdown-up .dropdown-contents {border-color: #de7300;}');
injectStyles('.dropdown li, .dropdown li li {border-color: #de7300;}');
injectStyles('.dropdown li.separator {border-color: #De7300;}');
injectStyles('.badge {background-color: #de7300;}');
injectStyles('.badge:before {border-bottom: 7.22px solid #de7300;}');
injectStyles('.badge:after {border-top: 7.22px solid #de7300;}');
injectStyles('.pagination li.active span {color: #de7300;}');
injectStyles('.pagination .button {background-color: #de7300;}');
injectStyles('.pagination .button:hover, .pagination .button:focus, .pagination .button:active {background-color: #de7300;}');
injectStyles('.pagination .button:before {border-bottom: 9.24px solid #de7300;}');
injectStyles('.pagination .button:after {border-top: 9.24px solid #de7300;}');
injectStyles('.row .pagination li a {background-color: #de7300;}');
injectStyles('.row .pagination li a:before {border-bottom: 6.35px solid #de7300;}');
injectStyles('.row .pagination li a:after {border-top: 6.35px solid #de7300;}');
injectStyles('.custombbcode {background-color: #de7300;}');
injectStyles('.custombbcode:hover {background-color: #de7300; box-shadow: 0 0 4px #de7300;}');
injectStyles('.collapse-btn:hover, .collapse-btn:focus { box-shadow: 0 0 20px 3px #de7300;}');
injectStyles('.collapse-show {background-color: #de7300;}');
injectStyles('.collapse-show:before {border-bottom: 5.22px solid #de7300;}');
injectStyles('.collapse-show:after {border-top: 5.22px solid #de7300;}');
injectStyles('.collapse-btn:hover {background-color: #de7300;}');
injectStyles('.postlink:visited { color: #d49451; }');
injectStyles('.icon.icon-orange, a:hover .icon.icon-orange { color: #FF6600; }');
injectStyles('.jumpbox-cat-link { background-color: #bd6200; }');
injectStyles('.pollbar2 { background-color: #f38005; }');
injectStyles('.pollbar3 { background-color: #ef7f07; }');
injectStyles('.pollbar4 { background-color: #cd6907; }');
injectStyles('.pollbar5 { background-color: #c56907; }');
injectStyles('.contact-icon:before {color: #de7300;}');
injectStyles('.site_logo { background-image: url(styles/HexagonReborn/theme/images/logo.png); }');
injectStyles('@media (max-width: 700px){ .logo { background-image: url(styles/HexagonReborn/theme/images/logo-med.png); }}');
injectStyles('.loading_indicator { background-image: url(styles/HexagonReborn/theme/images/loading.gif); }');

		$.cookie('colorpickerHexagonReborn', null, { path: '/' });
    });
	
	// When green is clicked:
    $('.colorgreen').click(function() {

injectStyles('a:hover,a:focus,a:active{color: #00de1f;}');
injectStyles('.button:before {color: #00de1f;}');
injectStyles('ul.navlinks {border-top: 1px solid #00de1f;}');
injectStyles('.minitabs .tab > a:hover {background-color: #00de1f;}');
injectStyles('.attach-image img {border-color: #00de1f !important;}');
injectStyles('dd input, dd textarea {border: 1px solid #00de1f;}');
injectStyles('.icon, .button .icon, blockquote cite:before, .uncited:before {color: #00de1f;}');
injectStyles('.dropdown-contents a:hover {color: #00de1f;}');
injectStyles('.profile-left {border-color: #00de1f;}');
injectStyles('@media (max-width: 700px){.inputbox {border: 1px solid #00de1f;}}');
injectStyles('.smiley-box:hover {border: 1px dashed #00de1f;}');
injectStyles('@media (max-width: 700px){.smiley-box {border: 1px dashed #00de1f;}}');
injectStyles('a.responsive-tab-link.dropdown-toggle:active{border: 1px solid #00de1f;}');
injectStyles('a.responsive-tab-link.dropdown-toggle:hover{border: 1px solid #00de1f;}');
injectStyles('.header{border-bottom: 4px solid #00de1f;}');
injectStyles('.global_unread:before,.global_unread_mine:before,.announce_unread:before,.announce_unread_mine:before,.sticky_unread:before,.sticky_unread_mine:before {color: #00de1f;}');
injectStyles('.global_unread_locked:before,.global_unread_locked_mine:before,.announce_unread_locked:before,.announce_unread_locked_mine:before,.forum_unread_locked:before,.topic_unread_locked:before,.topic_unread_locked_mine:before {color: #00de1f;}');
injectStyles('.forum_link:before {color: #00de1f;}');
injectStyles('.forum_unread:before,.forum_unread_subforum:before,.topic_unread:before,.topic_unread_mine:before {color: #00de1f;}');
injectStyles('.sticky_unread_locked:before,.sticky_unread_locked_mine:before {color: #00de1f;}');
injectStyles('.topic_unread_hot:before,.topic_unread_hot_mine:before {color: #00de1f;}');
injectStyles('.pm_unread:before {color: #00de1f;}');
injectStyles('.forum_read_subforum:after{color: #00de1f;}');
injectStyles('.forum_read_locked:after,.global_read_locked:after,.global_read_locked_mine:after,.announce_read_locked:after,.announce_read_locked_mine:after,.sticky_read_locked:after,.sticky_read_locked_mine:after,.topic_read_locked:after,.topic_read_locked_mine:after{color: #00de1f;}');
injectStyles('.dropdown-contents a:hover {color: #00de1f;}');
injectStyles('h3 {border-color: #00de1f;}');
injectStyles('hr {border-color: #00de1f;}');
injectStyles('a:hover {color: #00de1f;}');
injectStyles('.forumbg .header a:hover, .forabg .header a:hover, th a:hover {color: #00de1f;}');
injectStyles('.postlink {border-bottom-color: #00de1f;color: #00de1f;}');
injectStyles('.top i {color: #00de1f;}');
injectStyles('.arrow-left:hover, .arrow-right:hover {color: #00de1f;}');
injectStyles('.wrap {border-color: #00de1f;}');
injectStyles('table.table1 tbody th {border-bottom-color: #00de1f;}');
injectStyles('dl.details dt {color: #00de1f;}');
injectStyles('.sep {color: #00de1f;}');
injectStyles('.icon.icon-red, a:hover .icon.icon-red{color: #00de1f;}');
injectStyles('.icon.icon-black, a:hover .icon.icon-black{color: #00de1f;}');
injectStyles('.jumpbox .dropdown li {border-top-color: #00de1f;}');
injectStyles('.jumpbox-cat-link:hover {background-color: #00de1f;}');
injectStyles('.jumpbox .dropdown .pointer-inner {border-color: #00de1f transparent;}');
injectStyles('.copyright {color: #00de1f;}');
injectStyles('div.rules {background-color: #00de1f;}');
injectStyles('ul.topiclist dd {border-left-color: #00de1f;}');
injectStyles('li.row strong {color: #00de1f;}');
injectStyles('.rtl li.row:hover dd {border-right-color: #00de1f;}');
injectStyles('.content h2, .panel h2 {border-bottom-color: #00de1f;}');
injectStyles('dl.faq dt {color: #00de1f;}');
injectStyles('.posthilit {background-color: #00de1f;}');
injectStyles('.signature {border-top-color: #00de1f;}');
injectStyles('.notice {border-top-color:  #00de1f;}');
injectStyles('blockquote {border-color: #00de1f;}');
injectStyles('.codebox {border-color: #00de1f;}');
injectStyles('.attachbox {border-color: #00de1f;}');
injectStyles('dl.thumbnail img {border-color: #00de1f;}');
injectStyles('dl.thumbnail dt a:hover img {border-color: #00de1f;}');
injectStyles('fieldset.polls dl {border-top-color: #00de1f;}');
injectStyles('fieldset.polls dl.voted {color: #00de1f;}');
injectStyles('.pollbar1 {background-color: #00de1f;}');
injectStyles('.postprofile {border-color: #00de1f;}');
injectStyles('.pm .postprofile {border-color: #00de1f;}');
injectStyles('.postprofile strong {color: #00de1f;}');
injectStyles('.online {border-right: 5px solid #00de1f;}');
injectStyles('.button:hover,.button:focus ,.button:active{text-shadow: 0px 0px 10px #00de1f;}');
injectStyles('.button-search:hover,.button-search-end:hover {border-color: #00de1f;}');
injectStyles('.pagination li.ellipsis span {color: #00de1f;}');
injectStyles('.panel-container h3, .panel-container hr, .cp-menu hr {border-color: #00de1f;}');
injectStyles('.cp-main .pm-message {border-color: #00de1f;}');
injectStyles('.tabs .tab > a:hover {background: #00de1f;}');
injectStyles('.tabs .activetab > a,.tabs .activetab > a:hover {background-color: #00de1f;border-color: #00de1f;}');
injectStyles('.minitabs .activetab > a,.minitabs .activetab > a:hover {background-color: #00de1f;}');
injectStyles('.responsive-tab .responsive-tab-link:before {border-color: #00de1f;}');
injectStyles('.responsive-tab .responsive-tab-link:hover:before {border-color: #00de1f;}');
injectStyles('.rtl .navigation a {background: #00de1f;}');
injectStyles('.navigation a:hover {background: #00de1f;}');
injectStyles('.navigation .active-subsection a {background: #00de1f !important;}');
injectStyles('.gallery label {border-color: #00de1f;}');
injectStyles('select {border-color: #00de1f;color: #00de1f;}');
injectStyles('fieldset dl:hover dt label {color: #00de1f;}');
injectStyles('.inputbox:hover {box-shadow: 0 0 4px #00de1f;}');
injectStyles('.inputbox:focus {box-shadow: 0 0 4px #00de1f;}');
injectStyles('a.button1, input.button1, input.button3, a.button2, input.button2 {background-color: #00de1f;}');
injectStyles('a.button1, input.button1 {border-color: #00de1f;}');
injectStyles('a.button2, input.button2, input.button3 {border-color: #00de1f;}');
injectStyles('a.button1:hover, input.button1:hover, a.button2:hover, input.button2:hover, input.button3:hover {color: #00de1f;}');
injectStyles('input.button1:focus, input.button2:focus, input.button3:focus {border-color: #00de1f;}');
injectStyles('.phpbb_alert {border-color: #00de1f;}');
injectStyles('.dropdown-extended ul li {border-top-color: #00de1f;}');
injectStyles('.dropdown-extended ul li:hover {color: #00de1f;}');
injectStyles('.dropdown-extended .header, .dropdown-extended .footer {border-color: #00de1f;}');
injectStyles('.dropdown .pointer-inner {border-color: #00de1f transparent;}');
injectStyles('.dropdown-extended .pointer-inner {border-color: #00de1f transparent;}');
injectStyles('.dropdown .dropdown-contents {border-top: 2px solid #00de1f;}');
injectStyles('.dropdown-up .dropdown-contents {border-color: #00de1f;}');
injectStyles('.dropdown li, .dropdown li li {border-color: #00de1f;}');
injectStyles('.dropdown li.separator {border-color: #00de1f;}');
injectStyles('.badge {background-color: #00de1f;}');
injectStyles('.badge:before {border-bottom: 7.22px solid #00de1f;}');
injectStyles('.badge:after {border-top: 7.22px solid #00de1f;}');
injectStyles('.pagination li.active span {color: #00de1f;}');
injectStyles('.pagination .button {background-color: #00de1f;}');
injectStyles('.pagination .button:hover, .pagination .button:focus, .pagination .button:active {background-color: #00de1f;}');
injectStyles('.pagination .button:before {border-bottom: 9.24px solid #00de1f;}');
injectStyles('.pagination .button:after {border-top: 9.24px solid #00de1f;}');
injectStyles('.row .pagination li a {background-color: #00de1f;}');
injectStyles('.row .pagination li a:before {border-bottom: 6.35px solid #00de1f;}');
injectStyles('.row .pagination li a:after {border-top: 6.35px solid #00de1f;}');
injectStyles('.custombbcode {background-color: #00de1f;}');
injectStyles('.custombbcode:hover {background-color: #00de1f; box-shadow: 0 0 4px #00de1f;}');
injectStyles('.collapse-btn:hover, .collapse-btn:focus { box-shadow: 0 0 20px 3px #00de1f;}');
injectStyles('.collapse-show {background-color: #00de1f;}');
injectStyles('.collapse-show:before {border-bottom: 5.22px solid #00de1f;}');
injectStyles('.collapse-show:after {border-top: 5.22px solid #00de1f;}');
injectStyles('.collapse-btn:hover {background-color: #00de1f;}');
injectStyles('.postlink:visited { color: #51d363; }');
injectStyles('.icon.icon-orange, a:hover .icon.icon-orange { color: #00ff24; }');
injectStyles('.jumpbox-cat-link { background-color: #00bc1a; }');
injectStyles('.pollbar2 { background-color: #06f227; }');
injectStyles('.pollbar3 { background-color: #08ef28; }');
injectStyles('.pollbar4 { background-color: #07cc23; }');
injectStyles('.pollbar5 { background-color: #08c422; }');
injectStyles('.contact-icon:before {color: #00de1f;}');
injectStyles('.site_logo { background-image: url(styles/HexagonReborn/theme/images/logogreen.png); }');
injectStyles('@media (max-width: 700px){ .logo { background-image: url(styles/HexagonReborn/theme/images/logo-green-med.png); }}');
injectStyles('.loading_indicator { background-image: url(styles/HexagonReborn/theme/images/loadinggreen.gif); }');			

		
		$.cookie('colorpickerHexagonReborn', 'green', { path: '/' });
    });
// When blue is clicked:
    $('.colorblue').click(function() {
		
injectStyles('a:hover,a:focus,a:active{color: #0092de;}');
injectStyles('.button:before {color: #0092de;}');
injectStyles('ul.navlinks {border-top: 1px solid #0092de;}');
injectStyles('.minitabs .tab > a:hover {background-color: #0092de;}');
injectStyles('.attach-image img {border-color: #0092de !important;}');
injectStyles('dd input, dd textarea {border: 1px solid #0092de;}');
injectStyles('.icon, .button .icon, blockquote cite:before, .uncited:before {color: #0092de;}');
injectStyles('.dropdown-contents a:hover {color: #0092de;}');
injectStyles('.profile-left {border-color: #0092de;}');
injectStyles('@media (max-width: 700px){.inputbox {border: 1px solid #0092de;}}');
injectStyles('.smiley-box:hover {border: 1px dashed #0092de;}');
injectStyles('@media (max-width: 700px){.smiley-box {border: 1px dashed #0092de;}}');
injectStyles('a.responsive-tab-link.dropdown-toggle:active{border: 1px solid #0092de;}');
injectStyles('a.responsive-tab-link.dropdown-toggle:hover{border: 1px solid #0092de;}');
injectStyles('.header{border-bottom: 4px solid #0092de;}');
injectStyles('.global_unread:before,.global_unread_mine:before,.announce_unread:before,.announce_unread_mine:before,.sticky_unread:before,.sticky_unread_mine:before {color: #0092de;}');
injectStyles('.global_unread_locked:before,.global_unread_locked_mine:before,.announce_unread_locked:before,.announce_unread_locked_mine:before,.forum_unread_locked:before,.topic_unread_locked:before,.topic_unread_locked_mine:before {color: #0092de;}');
injectStyles('.forum_link:before {color: #0092de;}');
injectStyles('.forum_unread:before,.forum_unread_subforum:before,.topic_unread:before,.topic_unread_mine:before {color: #0092de;}');
injectStyles('.sticky_unread_locked:before,.sticky_unread_locked_mine:before {color: #0092de;}');
injectStyles('.topic_unread_hot:before,.topic_unread_hot_mine:before {color: #0092de;}');
injectStyles('.pm_unread:before {color: #0092de;}');
injectStyles('.forum_read_subforum:after{color: #0092de;}');
injectStyles('.forum_read_locked:after,.global_read_locked:after,.global_read_locked_mine:after,.announce_read_locked:after,.announce_read_locked_mine:after,.sticky_read_locked:after,.sticky_read_locked_mine:after,.topic_read_locked:after,.topic_read_locked_mine:after{color: #0092de;}');
injectStyles('.dropdown-contents a:hover {color: #0092de;}');
injectStyles('h3 {border-color: #0092de;}');
injectStyles('hr {border-color: #0092de;}');
injectStyles('a:hover {color: #0092de;}');
injectStyles('.forumbg .header a:hover, .forabg .header a:hover, th a:hover {color: #0092de;}');
injectStyles('.postlink {border-bottom-color: #0092de;color: #0092de;}');
injectStyles('.top i {color: #0092de;}');
injectStyles('.arrow-left:hover, .arrow-right:hover {color: #0092de;}');
injectStyles('.wrap {border-color: #0092de;}');
injectStyles('table.table1 tbody th {border-bottom-color: #0092de;}');
injectStyles('dl.details dt {color: #0092de;}');
injectStyles('.sep {color: #0092de;}');
injectStyles('.icon.icon-red, a:hover .icon.icon-red{color: #0092de;}');
injectStyles('.icon.icon-black, a:hover .icon.icon-black{color: #0092de;}');
injectStyles('.jumpbox .dropdown li {border-top-color: #0092de;}');
injectStyles('.jumpbox-cat-link:hover {background-color: #0092de;}');
injectStyles('.jumpbox .dropdown .pointer-inner {border-color: #0092de transparent;}');
injectStyles('.copyright {color: #0092de;}');
injectStyles('div.rules {background-color: #0092de;}');
injectStyles('ul.topiclist dd {border-left-color: #0092de;}');
injectStyles('li.row strong {color: #0092de;}');
injectStyles('.rtl li.row:hover dd {border-right-color: #0092de;}');
injectStyles('.content h2, .panel h2 {border-bottom-color: #0092de;}');
injectStyles('dl.faq dt {color: #0092de;}');
injectStyles('.posthilit {background-color: #0092de;}');
injectStyles('.signature {border-top-color: #0092de;}');
injectStyles('.notice {border-top-color:  #0092de;}');
injectStyles('blockquote {border-color: #0092de;}');
injectStyles('.codebox {border-color: #0092de;}');
injectStyles('.attachbox {border-color: #0092de;}');
injectStyles('dl.thumbnail img {border-color: #0092de;}');
injectStyles('dl.thumbnail dt a:hover img {border-color: #0092de;}');
injectStyles('fieldset.polls dl {border-top-color: #0092de;}');
injectStyles('fieldset.polls dl.voted {color: #0092de;}');
injectStyles('.pollbar1 {background-color: #0092de;}');
injectStyles('.postprofile {border-color: #0092de;}');
injectStyles('.pm .postprofile {border-color: #0092de;}');
injectStyles('.postprofile strong {color: #0092de;}');
injectStyles('.online {border-right: 5px solid #0092de;}');
injectStyles('.button:hover,.button:focus ,.button:active{text-shadow: 0px 0px 10px #0092de;}');
injectStyles('.button-search:hover,.button-search-end:hover {border-color: #0092de;}');
injectStyles('.pagination li.ellipsis span {color: #0092de;}');
injectStyles('.panel-container h3, .panel-container hr, .cp-menu hr {border-color: #0092de;}');
injectStyles('.cp-main .pm-message {border-color: #0092de;}');
injectStyles('.tabs .tab > a:hover {background: #0092de;}');
injectStyles('.tabs .activetab > a,.tabs .activetab > a:hover {background-color: #0092de;border-color: #0092de;}');
injectStyles('.minitabs .activetab > a,.minitabs .activetab > a:hover {background-color: #0092de;}');
injectStyles('.responsive-tab .responsive-tab-link:before {border-color: #0092de;}');
injectStyles('.responsive-tab .responsive-tab-link:hover:before {border-color: #0092de;}');
injectStyles('.rtl .navigation a {background: #0092de;}');
injectStyles('.navigation a:hover {background: #0092de;}');
injectStyles('.navigation .active-subsection a {background: #0092de !important;}');
injectStyles('.gallery label {border-color: #0092de;}');
injectStyles('select {border-color: #0092de;color: #0092de;}');
injectStyles('fieldset dl:hover dt label {color: #0092de;}');
injectStyles('.inputbox:hover {box-shadow: 0 0 4px #0092de;}');
injectStyles('.inputbox:focus {box-shadow: 0 0 4px #0092de;}');
injectStyles('a.button1, input.button1, input.button3, a.button2, input.button2 {background-color: #0092de;}');
injectStyles('a.button1, input.button1 {border-color: #0092de;}');
injectStyles('a.button2, input.button2, input.button3 {border-color: #0092de;}');
injectStyles('a.button1:hover, input.button1:hover, a.button2:hover, input.button2:hover, input.button3:hover {color: #0092de;}');
injectStyles('input.button1:focus, input.button2:focus, input.button3:focus {border-color: #0092de;}');
injectStyles('.phpbb_alert {border-color: #0092de;}');
injectStyles('.dropdown-extended ul li {border-top-color: #0092de;}');
injectStyles('.dropdown-extended ul li:hover {color: #0092de;}');
injectStyles('.dropdown-extended .header, .dropdown-extended .footer {border-color: #0092de;}');
injectStyles('.dropdown .pointer-inner {border-color: #0092de transparent;}');
injectStyles('.dropdown-extended .pointer-inner {border-color: #0092de transparent;}');
injectStyles('.dropdown .dropdown-contents {border-top: 2px solid #0092de;}');
injectStyles('.dropdown-up .dropdown-contents {border-color: #0092de;}');
injectStyles('.dropdown li, .dropdown li li {border-color: #0092de;}');
injectStyles('.dropdown li.separator {border-color: #0092de;}');
injectStyles('.badge {background-color: #0092de;}');
injectStyles('.badge:before {border-bottom: 7.22px solid #0092de;}');
injectStyles('.badge:after {border-top: 7.22px solid #0092de;}');
injectStyles('.pagination li.active span {color: #0092de;}');
injectStyles('.pagination .button {background-color: #0092de;}');
injectStyles('.pagination .button:hover, .pagination .button:focus, .pagination .button:active {background-color: #0092de;}');
injectStyles('.pagination .button:before {border-bottom: 9.24px solid #0092de;}');
injectStyles('.pagination .button:after {border-top: 9.24px solid #0092de;}');
injectStyles('.row .pagination li a {background-color: #0092de;}');
injectStyles('.row .pagination li a:before {border-bottom: 6.35px solid #0092de;}');
injectStyles('.row .pagination li a:after {border-top: 6.35px solid #0092de;}');
injectStyles('.custombbcode {background-color: #0092de;}');
injectStyles('.custombbcode:hover {background-color: #0092de; box-shadow: 0 0 4px #0092de;}');
injectStyles('.collapse-btn:hover, .collapse-btn:focus { box-shadow: 0 0 20px 3px #0092de;}');
injectStyles('.collapse-show {background-color: #0092de;}');
injectStyles('.collapse-show:before {border-bottom: 5.22px solid #0092de;}');
injectStyles('.collapse-show:after {border-top: 5.22px solid #0092de;}');
injectStyles('.collapse-btn:hover {background-color: #0092de;}');
injectStyles('.postlink:visited { color: #51a7d3; }');
injectStyles('.icon.icon-orange, a:hover .icon.icon-orange { color: #00a7fe; }');
injectStyles('.jumpbox-cat-link { background-color: #00a4bd; }');
injectStyles('.pollbar2 { background-color: #06a2f3; }');
injectStyles('.pollbar3 { background-color: #079fee; }');
injectStyles('.pollbar4 { background-color: #0789cd; }');
injectStyles('.pollbar5 { background-color: #0884c5; }');
injectStyles('.contact-icon:before {color: #0092de;}');
injectStyles('.site_logo { background-image: url(styles/HexagonReborn/theme/images/logoblue.png); }');
injectStyles('@media (max-width: 700px){ .logo { background-image: url(styles/HexagonReborn/theme/images/logo-blue-med.png); }}');
injectStyles('.loading_indicator { background-image: url(styles/HexagonReborn/theme/images/loadingblue.gif); }');

		$.cookie('colorpickerHexagonReborn', 'blue', { path: '/' });
    });
// When cyan is clicked:
    $('.colorcyan').click(function() {
		
injectStyles('a:hover,a:focus,a:active{color: #00c1de;}');
injectStyles('.button:before {color: #00c1de;}');
injectStyles('ul.navlinks {border-top: 1px solid #00c1de;}');
injectStyles('.minitabs .tab > a:hover {background-color: #00c1de;}');
injectStyles('.attach-image img {border-color: #00c1de !important;}');
injectStyles('dd input, dd textarea {border: 1px solid #00c1de;}');
injectStyles('.icon, .button .icon, blockquote cite:before, .uncited:before {color: #00c1de;}');
injectStyles('.dropdown-contents a:hover {color: #00c1de;}');
injectStyles('.profile-left {border-color: #00c1de;}');
injectStyles('@media (max-width: 700px){.inputbox {border: 1px solid #00c1de;}}');
injectStyles('.smiley-box:hover {border: 1px dashed #00c1de;}');
injectStyles('@media (max-width: 700px){.smiley-box {border: 1px dashed #00c1de;}}');
injectStyles('a.responsive-tab-link.dropdown-toggle:active{border: 1px solid #00c1de;}');
injectStyles('a.responsive-tab-link.dropdown-toggle:hover{border: 1px solid #00c1de;}');
injectStyles('.header{border-bottom: 4px solid #00c1de;}');
injectStyles('.global_unread:before,.global_unread_mine:before,.announce_unread:before,.announce_unread_mine:before,.sticky_unread:before,.sticky_unread_mine:before {color: #00c1de;}');
injectStyles('.global_unread_locked:before,.global_unread_locked_mine:before,.announce_unread_locked:before,.announce_unread_locked_mine:before,.forum_unread_locked:before,.topic_unread_locked:before,.topic_unread_locked_mine:before {color: #00c1de;}');
injectStyles('.forum_link:before {color: #00c1de;}');
injectStyles('.forum_unread:before,.forum_unread_subforum:before,.topic_unread:before,.topic_unread_mine:before {color: #00c1de;}');
injectStyles('.sticky_unread_locked:before,.sticky_unread_locked_mine:before {color: #00c1de;}');
injectStyles('.topic_unread_hot:before,.topic_unread_hot_mine:before {color: #00c1de;}');
injectStyles('.pm_unread:before {color: #00c1de;}');
injectStyles('.forum_read_subforum:after{color: #00c1de;}');
injectStyles('.forum_read_locked:after,.global_read_locked:after,.global_read_locked_mine:after,.announce_read_locked:after,.announce_read_locked_mine:after,.sticky_read_locked:after,.sticky_read_locked_mine:after,.topic_read_locked:after,.topic_read_locked_mine:after{color: #00c1de;}');
injectStyles('.dropdown-contents a:hover {color: #00c1de;}');
injectStyles('h3 {border-color: #00c1de;}');
injectStyles('hr {border-color: #00c1de;}');
injectStyles('a:hover {color: #00c1de;}');
injectStyles('.forumbg .header a:hover, .forabg .header a:hover, th a:hover {color: #00c1de;}');
injectStyles('.postlink {border-bottom-color: #00c1de;color: #00c1de;}');
injectStyles('.top i {color: #00c1de;}');
injectStyles('.arrow-left:hover, .arrow-right:hover {color: #00c1de;}');
injectStyles('.wrap {border-color: #00c1de;}');
injectStyles('table.table1 tbody th {border-bottom-color: #00c1de;}');
injectStyles('dl.details dt {color: #00c1de;}');
injectStyles('.sep {color: #00c1de;}');
injectStyles('.icon.icon-red, a:hover .icon.icon-red{color: #00c1de;}');
injectStyles('.icon.icon-black, a:hover .icon.icon-black{color: #00c1de;}');
injectStyles('.jumpbox .dropdown li {border-top-color: #00c1de;}');
injectStyles('.jumpbox-cat-link:hover {background-color: #00c1de;}');
injectStyles('.jumpbox .dropdown .pointer-inner {border-color: #00c1de transparent;}');
injectStyles('.copyright {color: #00c1de;}');
injectStyles('div.rules {background-color: #00c1de;}');
injectStyles('ul.topiclist dd {border-left-color: #00c1de;}');
injectStyles('li.row strong {color: #00c1de;}');
injectStyles('.rtl li.row:hover dd {border-right-color: #00c1de;}');
injectStyles('.content h2, .panel h2 {border-bottom-color: #00c1de;}');
injectStyles('dl.faq dt {color: #00c1de;}');
injectStyles('.posthilit {background-color: #00c1de;}');
injectStyles('.signature {border-top-color: #00c1de;}');
injectStyles('.notice {border-top-color:  #00c1de;}');
injectStyles('blockquote {border-color: #00c1de;}');
injectStyles('.codebox {border-color: #00c1de;}');
injectStyles('.attachbox {border-color: #00c1de;}');
injectStyles('dl.thumbnail img {border-color: #00c1de;}');
injectStyles('dl.thumbnail dt a:hover img {border-color: #00c1de;}');
injectStyles('fieldset.polls dl {border-top-color: #00c1de;}');
injectStyles('fieldset.polls dl.voted {color: #00c1de;}');
injectStyles('.pollbar1 {background-color: #00c1de;}');
injectStyles('.postprofile {border-color: #00c1de;}');
injectStyles('.pm .postprofile {border-color: #00c1de;}');
injectStyles('.postprofile strong {color: #00c1de;}');
injectStyles('.online {border-right: 5px solid #00c1de;}');
injectStyles('.button:hover,.button:focus ,.button:active{text-shadow: 0px 0px 10px #00c1de;}');
injectStyles('.button-search:hover,.button-search-end:hover {border-color: #00c1de;}');
injectStyles('.pagination li.ellipsis span {color: #00c1de;}');
injectStyles('.panel-container h3, .panel-container hr, .cp-menu hr {border-color: #00c1de;}');
injectStyles('.cp-main .pm-message {border-color: #00c1de;}');
injectStyles('.tabs .tab > a:hover {background: #00c1de;}');
injectStyles('.tabs .activetab > a,.tabs .activetab > a:hover {background-color: #00c1de;border-color: #00c1de;}');
injectStyles('.minitabs .activetab > a,.minitabs .activetab > a:hover {background-color: #00c1de;}');
injectStyles('.responsive-tab .responsive-tab-link:before {border-color: #00c1de;}');
injectStyles('.responsive-tab .responsive-tab-link:hover:before {border-color: #00c1de;}');
injectStyles('.rtl .navigation a {background: #00c1de;}');
injectStyles('.navigation a:hover {background: #00c1de;}');
injectStyles('.navigation .active-subsection a {background: #00c1de !important;}');
injectStyles('.gallery label {border-color: #00c1de;}');
injectStyles('select {border-color: #00c1de;color: #00c1de;}');
injectStyles('fieldset dl:hover dt label {color: #00c1de;}');
injectStyles('.inputbox:hover {box-shadow: 0 0 4px #00c1de;}');
injectStyles('.inputbox:focus {box-shadow: 0 0 4px #00c1de;}');
injectStyles('a.button1, input.button1, input.button3, a.button2, input.button2 {background-color: #00c1de;}');
injectStyles('a.button1, input.button1 {border-color: #00c1de;}');
injectStyles('a.button2, input.button2, input.button3 {border-color: #00c1de;}');
injectStyles('a.button1:hover, input.button1:hover, a.button2:hover, input.button2:hover, input.button3:hover {color: #00c1de;}');
injectStyles('input.button1:focus, input.button2:focus, input.button3:focus {border-color: #00c1de;}');
injectStyles('.phpbb_alert {border-color: #00c1de;}');
injectStyles('.dropdown-extended ul li {border-top-color: #00c1de;}');
injectStyles('.dropdown-extended ul li:hover {color: #00c1de;}');
injectStyles('.dropdown-extended .header, .dropdown-extended .footer {border-color: #00c1de;}');
injectStyles('.dropdown .pointer-inner {border-color: #00c1de transparent;}');
injectStyles('.dropdown-extended .pointer-inner {border-color: #00c1de transparent;}');
injectStyles('.dropdown .dropdown-contents {border-top: 2px solid #00c1de;}');
injectStyles('.dropdown-up .dropdown-contents {border-color: #00c1de;}');
injectStyles('.dropdown li, .dropdown li li {border-color: #00c1de;}');
injectStyles('.dropdown li.separator {border-color: #00c1de;}');
injectStyles('.badge {background-color: #00c1de;}');
injectStyles('.badge:before {border-bottom: 7.22px solid #00c1de;}');
injectStyles('.badge:after {border-top: 7.22px solid #00c1de;}');
injectStyles('.pagination li.active span {color: #00c1de;}');
injectStyles('.pagination .button {background-color: #00c1de;}');
injectStyles('.pagination .button:hover, .pagination .button:focus, .pagination .button:active {background-color: #00c1de;}');
injectStyles('.pagination .button:before {border-bottom: 9.24px solid #00c1de;}');
injectStyles('.pagination .button:after {border-top: 9.24px solid #00c1de;}');
injectStyles('.row .pagination li a {background-color: #00c1de;}');
injectStyles('.row .pagination li a:before {border-bottom: 6.35px solid #00c1de;}');
injectStyles('.row .pagination li a:after {border-top: 6.35px solid #00c1de;}');
injectStyles('.custombbcode {background-color: #00c1de;}');
injectStyles('.custombbcode:hover {background-color: #00c1de; box-shadow: 0 0 4px #00c1de;}');
injectStyles('.collapse-btn:hover, .collapse-btn:focus { box-shadow: 0 0 20px 3px #00c1de;}');
injectStyles('.collapse-show {background-color: #00c1de;}');
injectStyles('.collapse-show:before {border-bottom: 5.22px solid #00c1de;}');
injectStyles('.collapse-show:after {border-top: 5.22px solid #00c1de;}');
injectStyles('.collapse-btn:hover {background-color: #7d00de;}');
injectStyles('.postlink:visited { color: #51c1d2; }');
injectStyles('.icon.icon-orange, a:hover .icon.icon-orange { color: #01deff; }');
injectStyles('.jumpbox-cat-link { background-color: #00a4bd; }');
injectStyles('.pollbar2 { background-color: #06d4f3; }');
injectStyles('.pollbar3 { background-color: #07d0ee; }');
injectStyles('.pollbar4 { background-color: #07b2cc; }');
injectStyles('.pollbar5 { background-color: #08acc5; }');
injectStyles('.contact-icon:before {color: #00c1de;}');
injectStyles('@media (max-width: 700px){ .inputbox { border: 1px solid #00c1de; }}');
injectStyles('@media (max-width: 700px){ .smiley-box { border: 1px dashed #00c1de; }}');
injectStyles('.site_logo { background-image: url(styles/HexagonReborn/theme/images/logocyan.png); }');
injectStyles('@media (max-width: 700px){ .logo { background-image: url(styles/HexagonReborn/theme/images/logo-cyan-med.png); }}');
injectStyles('.loading_indicator { background-image: url(styles/HexagonReborn/theme/images/loadingcyan.gif); }');

		$.cookie('colorpickerHexagonReborn', 'cyan', { path: '/' });
    });	
// When violet is clicked:
    $('.colorviolet').click(function() {
		
injectStyles('a:hover,a:focus,a:active{color: #7d00de;}');
injectStyles('.button:before {color: #7d00de;}');
injectStyles('ul.navlinks {border-top: 1px solid #7d00de;}');
injectStyles('.minitabs .tab > a:hover {background-color: #7d00de;}');
injectStyles('.attach-image img {border-color: #7d00de !important;}');
injectStyles('dd input, dd textarea {border: 1px solid #7d00de;}');
injectStyles('.icon, .button .icon, blockquote cite:before, .uncited:before {color: #7d00de;}');
injectStyles('.dropdown-contents a:hover {color: #7d00de;}');
injectStyles('.profile-left {border-color: #7d00de;}');
injectStyles('@media (max-width: 700px){.inputbox {border: 1px solid #7d00de;}}');
injectStyles('.smiley-box:hover {border: 1px dashed #7d00de;}');
injectStyles('@media (max-width: 700px){.smiley-box {border: 1px dashed #7d00de;}}');
injectStyles('a.responsive-tab-link.dropdown-toggle:active{border: 1px solid #7d00de;}');
injectStyles('a.responsive-tab-link.dropdown-toggle:hover{border: 1px solid #7d00de;}');
injectStyles('.header{border-bottom: 4px solid #7d00de;}');
injectStyles('.global_unread:before,.global_unread_mine:before,.announce_unread:before,.announce_unread_mine:before,.sticky_unread:before,.sticky_unread_mine:before {color: #7d00de;}');
injectStyles('.global_unread_locked:before,.global_unread_locked_mine:before,.announce_unread_locked:before,.announce_unread_locked_mine:before,.forum_unread_locked:before,.topic_unread_locked:before,.topic_unread_locked_mine:before {color: #7d00de;}');
injectStyles('.forum_link:before {color: #7d00de;}');
injectStyles('.forum_unread:before,.forum_unread_subforum:before,.topic_unread:before,.topic_unread_mine:before {color: #7d00de;}');
injectStyles('.sticky_unread_locked:before,.sticky_unread_locked_mine:before {color: #7d00de;}');
injectStyles('.topic_unread_hot:before,.topic_unread_hot_mine:before {color: #7d00de;}');
injectStyles('.pm_unread:before {color: #7d00de;}');
injectStyles('.forum_read_subforum:after{color: #7d00de;}');
injectStyles('.forum_read_locked:after,.global_read_locked:after,.global_read_locked_mine:after,.announce_read_locked:after,.announce_read_locked_mine:after,.sticky_read_locked:after,.sticky_read_locked_mine:after,.topic_read_locked:after,.topic_read_locked_mine:after{color: #7d00de;}');
injectStyles('.dropdown-contents a:hover {color: #7d00de;}');
injectStyles('h3 {border-color: #7d00de;}');
injectStyles('hr {border-color: #7d00de;}');
injectStyles('a:hover {color: #7d00de;}');
injectStyles('.forumbg .header a:hover, .forabg .header a:hover, th a:hover {color: #7d00de;}');
injectStyles('.postlink {border-bottom-color: #7d00de;color: #7d00de;}');
injectStyles('.top i {color: #7d00de;}');
injectStyles('.arrow-left:hover, .arrow-right:hover {color: #7d00de;}');
injectStyles('.wrap {border-color: #7d00de;}');
injectStyles('table.table1 tbody th {border-bottom-color: #7d00de;}');
injectStyles('dl.details dt {color: #7d00de;}');
injectStyles('.sep {color: #7d00de;}');
injectStyles('.icon.icon-red, a:hover .icon.icon-red{color: #7d00de;}');
injectStyles('.icon.icon-black, a:hover .icon.icon-black{color: #7d00de;}');
injectStyles('.jumpbox .dropdown li {border-top-color: #7d00de;}');
injectStyles('.jumpbox-cat-link:hover {background-color: #7d00de;}');
injectStyles('.jumpbox .dropdown .pointer-inner {border-color: #7d00de transparent;}');
injectStyles('.copyright {color: #7d00de;}');
injectStyles('div.rules {background-color: #7d00de;}');
injectStyles('ul.topiclist dd {border-left-color: #7d00de;}');
injectStyles('li.row strong {color: #7d00de;}');
injectStyles('.rtl li.row:hover dd {border-right-color: #7d00de;}');
injectStyles('.content h2, .panel h2 {border-bottom-color: #7d00de;}');
injectStyles('dl.faq dt {color: #7d00de;}');
injectStyles('.posthilit {background-color: #7d00de;}');
injectStyles('.signature {border-top-color: #7d00de;}');
injectStyles('.notice {border-top-color:  #7d00de;}');
injectStyles('blockquote {border-color: #7d00de;}');
injectStyles('.codebox {border-color: #7d00de;}');
injectStyles('.attachbox {border-color: #7d00de;}');
injectStyles('dl.thumbnail img {border-color: #7d00de;}');
injectStyles('dl.thumbnail dt a:hover img {border-color: #7d00de;}');
injectStyles('fieldset.polls dl {border-top-color: #7d00de;}');
injectStyles('fieldset.polls dl.voted {color: #7d00de;}');
injectStyles('.pollbar1 {background-color: #7d00de;}');
injectStyles('.postprofile {border-color: #7d00de;}');
injectStyles('.pm .postprofile {border-color: #7d00de;}');
injectStyles('.postprofile strong {color: #7d00de;}');
injectStyles('.online {border-right: 5px solid #7d00de;}');
injectStyles('.button:hover,.button:focus ,.button:active{text-shadow: 0px 0px 10px #7d00de;}');
injectStyles('.button-search:hover,.button-search-end:hover {border-color: #7d00de;}');
injectStyles('.pagination li.ellipsis span {color: #7d00de;}');
injectStyles('.panel-container h3, .panel-container hr, .cp-menu hr {border-color: #7d00de;}');
injectStyles('.cp-main .pm-message {border-color: #7d00de;}');
injectStyles('.tabs .tab > a:hover {background: #7d00de;}');
injectStyles('.tabs .activetab > a,.tabs .activetab > a:hover {background-color: #7d00de;border-color: #7d00de;}');
injectStyles('.minitabs .activetab > a,.minitabs .activetab > a:hover {background-color: #7d00de;}');
injectStyles('.responsive-tab .responsive-tab-link:before {border-color: #7d00de;}');
injectStyles('.responsive-tab .responsive-tab-link:hover:before {border-color: #7d00de;}');
injectStyles('.rtl .navigation a {background: #7d00de;}');
injectStyles('.navigation a:hover {background: #7d00de;}');
injectStyles('.navigation .active-subsection a {background: #7d00de !important;}');
injectStyles('.gallery label {border-color: #7d00de;}');
injectStyles('select {border-color: #7d00de;color: #7d00de;}');
injectStyles('fieldset dl:hover dt label {color: #7d00de;}');
injectStyles('.inputbox:hover {box-shadow: 0 0 4px #7d00de;}');
injectStyles('.inputbox:focus {box-shadow: 0 0 4px #7d00de;}');
injectStyles('a.button1, input.button1, input.button3, a.button2, input.button2 {background-color: #7d00de;}');
injectStyles('a.button1, input.button1 {border-color: #7d00de;}');
injectStyles('a.button2, input.button2, input.button3 {border-color: #7d00de;}');
injectStyles('a.button1:hover, input.button1:hover, a.button2:hover, input.button2:hover, input.button3:hover {color: #7d00de;}');
injectStyles('input.button1:focus, input.button2:focus, input.button3:focus {border-color: #7d00de;}');
injectStyles('.phpbb_alert {border-color: #7d00de;}');
injectStyles('.dropdown-extended ul li {border-top-color: #7d00de;}');
injectStyles('.dropdown-extended ul li:hover {color: #7d00de;}');
injectStyles('.dropdown-extended .header, .dropdown-extended .footer {border-color: #7d00de;}');
injectStyles('.dropdown .pointer-inner {border-color: #7d00de transparent;}');
injectStyles('.dropdown-extended .pointer-inner {border-color: #7d00de transparent;}');
injectStyles('.dropdown .dropdown-contents {border-top: 2px solid #7d00de;}');
injectStyles('.dropdown-up .dropdown-contents {border-color: #7d00de;}');
injectStyles('.dropdown li, .dropdown li li {border-color: #7d00de;}');
injectStyles('.dropdown li.separator {border-color: #7d00de;}');
injectStyles('.badge {background-color: #7d00de;}');
injectStyles('.badge:before {border-bottom: 7.22px solid #7d00de;}');
injectStyles('.badge:after {border-top: 7.22px solid #7d00de;}');
injectStyles('.pagination li.active span {color: #7d00de;}');
injectStyles('.pagination .button {background-color: #7d00de;}');
injectStyles('.pagination .button:hover, .pagination .button:focus, .pagination .button:active {background-color: #7d00de;}');
injectStyles('.pagination .button:before {border-bottom: 9.24px solid #7d00de;}');
injectStyles('.pagination .button:after {border-top: 9.24px solid #7d00de;}');
injectStyles('.row .pagination li a {background-color: #7d00de;}');
injectStyles('.row .pagination li a:before {border-bottom: 6.35px solid #7d00de;}');
injectStyles('.row .pagination li a:after {border-top: 6.35px solid #7d00de;}');
injectStyles('.custombbcode {background-color: #7d00de;}');
injectStyles('.custombbcode:hover {background-color: #7d00de; box-shadow: 0 0 4px #7d00de;}');
injectStyles('.collapse-btn:hover, .collapse-btn:focus { box-shadow: 0 0 20px 3px #7d00de;}');
injectStyles('.collapse-show {background-color: #7d00de;}');
injectStyles('.collapse-show:before {border-bottom: 5.22px solid #7d00de;}');
injectStyles('.collapse-show:after {border-top: 5.22px solid #7d00de;}');
injectStyles('.collapse-btn:hover {background-color: #7d00de;}');
injectStyles('.postlink:visited { color: #9b52d3; }');
injectStyles('.icon.icon-orange, a:hover .icon.icon-orange { color: #9001ff; }');
injectStyles('.jumpbox-cat-link { background-color: #6a00bd; }');
injectStyles('.pollbar2 { background-color: #8b06f3; }');
injectStyles('.pollbar3 { background-color: #8a08ef; }');
injectStyles('.pollbar4 { background-color: #7606cd; }');
injectStyles('.pollbar5 { background-color: #7207c5; }');
injectStyles('.contact-icon:before {color: #7d00de;}');
injectStyles('.site_logo { background-image: url(styles/HexagonReborn/theme/images/logoviolet.png); }');
injectStyles('@media (max-width: 700px){ .logo { background-image: url(styles/HexagonReborn/theme/images/logo-violet-med.png); }}');
injectStyles('.loading_indicator { background-image: url(styles/HexagonReborn/theme/images/loadingviolet.gif); }');

		$.cookie('colorpickerHexagonReborn', 'violet', { path: '/' });
    });	
});