services:
    tatiana5.profileSideSwitcher.listener:
        class: tatiana5\profileSideSwitcher\event\listener
        arguments:
        - @template
        - @user
        - @dbal.conn
        - @request
        - %core.root_path%
        - %core.php_ext%
        tags:
            - { name: event.listener }
